version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-cep
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock